version: '3'
services:
  app:
    build: .
#    user: node
    ports:
      - 8081:8081
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
#    command: "node old-app.js"
    command: "npm start"
#    links:
#      - rabbitmq
#      - mongodb
#
#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - 35672:5672
#      - 45672:15672
#
#  mongodb:
#    image: mongo
#    volumes:
#      - ./db/:/data/db
#    ports:
#      - 127.0.0.1:27017:27017


